name: si_angkot
description: "Aplikasi monitoring angkot berbasis flutter"
publish_to: 'none'
version: 0.0.1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  get: ^4.1.4
  intl: ^0.18.0
  circular_image: ^0.0.6
  build_runner: ^2.4.15
  flutter_gen_runner: ^5.9.0
  shared_preferences: ^2.5.2
  flutter_svg: ^2.0.17
  simple_gradient_text: ^1.3.0
  qr_flutter: ^4.1.0
  qr_code_scanner_plus: ^2.0.10+1
  circle_avatar: ^1.0.1
  image_picker: ^1.1.2
  hugeicons: ^0.0.7
  geolocator: ^10.1.0
  web_socket_channel: ^2.4.0
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  firebase_database: ^11.3.4
  flutter_native_splash: ^2.3.1
  permission_handler: ^11.3.0 # opsional tambahan
  flutter_map: ^5.0.0
  latlong2: ^0.9.0

# akan generate folder lib/gen dan seisinya dengan perintah dart run build_runner build -d
# untuk mengenerate file assets, colors, dan fonts
# agar lebih mudah untuk memanggil asset,fonts,dan colors di dalam aplikasi
  vector_graphics: any



flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)
  line_length: 80 # Optional (default: 80)
  integrations:
    flutter_svg: true
  assets:
    enabled: true
    outputs:
      class_name: MyAssets
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
    outputs:
      class_name: MyColors
  fonts:
    enabled: true
    outputs:
      class_name: MyFonts

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/svg/
    - assets/png/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/poppins_light.ttf
          weight: 300
        - asset: assets/fonts/poppins_medium.ttf
          weight: 300
        - asset: assets/fonts/poppins_regular.ttf
          weight: 400
        - asset: assets/fonts/poppins_semibold.ttf
          weight: 600
        - asset: assets/fonts/poppins_bold.ttf
          weight: 700
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter_light.ttf
          weight: 300
        - asset: assets/fonts/Inter_medium.ttf
          weight: 300
        - asset: assets/fonts/Inter_regular.ttf
          weight: 400
        - asset: assets/fonts/Inter_semi_bold.ttf
          weight: 600
        - asset: assets/fonts/Inter_bold.ttf
          weight: 700


