// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDY1HXfDYIjcSwHOpug22oKWPwV5wDzdAk',
    appId: '1:1045505393657:web:ab793206ba1c864b5bf328',
    messagingSenderId: '1045505393657',
    projectId: 'si-angkot',
    authDomain: 'si-angkot.firebaseapp.com',
    databaseURL: 'https://si-angkot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-angkot.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2RYal7nLN3exCkxka9hYqwrRJMuxpEU0',
    appId: '1:1045505393657:android:514d14e36a6479965bf328',
    messagingSenderId: '1045505393657',
    projectId: 'si-angkot',
    databaseURL: 'https://si-angkot-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'si-angkot.firebasestorage.app',
  );

}